package com.example;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.opentelemetry.api.GlobalOpenTelemetry;
import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.StatusCode;
import io.opentelemetry.api.trace.Tracer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.Instant;
import java.util.Random;

/**
 * TelemetryReplayController
 *
 * Endpoint:
 * - GET /replay-last-10-mins
 *
 * Purpose:
 * - Replays 60 telemetry events covering the last 10 minutes.
 * - Simulates both normal load and incident scenarios (errors, latency spikes, CPU spikes).
 *
 * Behavior:
 * - Generates spans with attributes (user.id, action, error.type, etc.).
 * - Records metrics via Micrometer counters and CustomMetricsController.
 * - Stores events in InMemoryTraceStore for retrieval via /traces/last-10-mins.
 * - Logs detailed INFO/ERROR messages for observability testing.
 *
 * Usage:
 * - Call this endpoint to quickly populate the system with demo telemetry.
 * - ~30% chance of incident simulation to test alerting and dashboards.
 */

@RestController
public class TelemetryReplayController {

    private static final Logger logger = LoggerFactory.getLogger(TelemetryReplayController.class);
    private final Tracer tracer = GlobalOpenTelemetry.getTracer("replay-controller");

    private final Counter replayMetricCounter;
    private final Counter errorCounter;
    private final Counter latencySpikeCounter;
    private final Counter cpuSpikeCounter;
    private final InMemoryTraceStore traceStore;
    private final CustomMetricsController metricsController;
    public TelemetryReplayController(MeterRegistry registry , InMemoryTraceStore traceStore , CustomMetricsController metricsController) {

        this.metricsController = metricsController;
        this.replayMetricCounter = Counter.builder("replay.generated.events")
                .description("Number of simulated events generated by the replay endpoint")
                .register(registry);

        this.errorCounter = Counter.builder("replay.error.events")
                .description("Number of simulated error events")
                .register(registry);

        this.latencySpikeCounter = Counter.builder("incident.latency.spikes")
                .description("Number of latency spikes during incident simulation")
                .register(registry);

        this.cpuSpikeCounter = Counter.builder("incident.cpu.spikes")
                .description("Number of CPU spikes during incident simulation")
                .register(registry);
        this.traceStore = traceStore;
    }

    @GetMapping("/replay-last-10-mins")
    public String replay() {
        Random random = new Random();
        boolean simulateIncident = random.nextDouble() < 0.3;

        logger.info("REPLAY MODE: {}", simulateIncident ? "🚨 INCIDENT SIMULATION" : "Normal load");

        for (int i = 0; i < 60; i++) {
            String action = new String[]{"login", "purchase", "logout", "search"}[random.nextInt(4)];
            int userId = random.nextInt(1000);
            Instant fakeTime = Instant.now().minusSeconds(600 - (i * 10));

            Span span = tracer.spanBuilder("replay-span-" + i)
                    .setStartTimestamp(fakeTime)
                    .startSpan();

            String traceId = span.getSpanContext().getTraceId();
            String spanId = span.getSpanContext().getSpanId();

            span.setAttribute("user.id", userId);
            span.setAttribute("action", action);
            span.setAttribute("event.generated_at", fakeTime.toString());


            boolean isError = false;
            String errorType = null;

            if (simulateIncident && i % 7 == 0) {
                // Simulate error
                errorType = new String[]{"NullPointerException", "TimeoutException", "DBConnectionError"}[random.nextInt(3)];
                span.setAttribute("incident", true);
                span.setAttribute("error.type", errorType);
                span.setStatus(StatusCode.ERROR);
                errorCounter.increment();
                isError = true;

                long delay = 0;
                try {
                    delay = 1000 + random.nextInt(1000);
                    Thread.sleep(delay);
                    span.setAttribute("latency.spike.ms", delay);
                    latencySpikeCounter.increment();
                    metricsController.recordErrorEvent();
                    metricsController.recordLatencySpike();
                    metricsController.recordCpuSpike();
                    metricsController.recordHttp500();
                } catch (InterruptedException ignored) {}

                long cpuStart = System.nanoTime();
                long durationNs = (100 + random.nextInt(100)) * 1_000_000L;
                while (System.nanoTime() - cpuStart < durationNs) {
                    Math.pow(random.nextDouble(), random.nextDouble());
                }
                span.setAttribute("cpu.spike.ms", durationNs / 1_000_000);
                cpuSpikeCounter.increment();

                logger.error("INCIDENT [{}]: userId={}, action={}, errorType={}, latency={}ms",
                        i, userId, action, errorType, delay);
                span.setAttribute("http.status_code", 500);

            } else {
                logger.info("REPLAY [{}]: userId={}, action={}, at={}", i, userId, action, fakeTime);
                span.setAttribute("http.method", "GET");
                span.setAttribute("http.route", "/replay-last-10-mins");
                span.setAttribute("http.status_code", 200);
                metricsController.recordTotalEvent();
                metricsController.recordHttp200();
            }

            // ✅ Store the trace for later retrieval via /traces/last-10-mins
            traceStore.addTrace(new TraceEvent(traceId, spanId, action, userId, fakeTime, isError, errorType));

            replayMetricCounter.increment();

            span.end();
        }

        return simulateIncident
                ? "Incident simulation complete — 60 events generated with latency, CPU, and error spikes"
                : "Normal telemetry replay — 60 events generated";
    }
}
