package com.example;

import io.opentelemetry.api.GlobalOpenTelemetry;
import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.sdk.OpenTelemetrySdk;
import io.opentelemetry.sdk.trace.SdkTracerProvider;
import io.opentelemetry.sdk.trace.export.SimpleSpanProcessor;
import io.opentelemetry.exporter.logging.LoggingSpanExporter;
import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import java.time.Instant;
import java.util.Random;
import io.opentelemetry.api.trace.StatusCode;

@Component
public class TelemetryGenerator {

    private static final Logger logger = LoggerFactory.getLogger(TelemetryGenerator.class);
    private Tracer tracer;
    private final Counter randomActionCounter;
    private final Counter errorCounter;
    private final InMemoryTraceStore traceStore;
    private final CustomMetricsController metricsController;
    private final Counter latencySpikeCounter;
    private final Counter cpuSpikeCounter;
    private final Counter replayMetricCounter;

    public TelemetryGenerator(MeterRegistry registry , CustomMetricsController metricsController , InMemoryTraceStore traceStore) {
        this.randomActionCounter = Counter.builder("random.action.count")
                .description("Counts how many random actions were generated")
                .register(registry);
        this.metricsController = metricsController;
        this.traceStore = traceStore;
        this.errorCounter = Counter.builder("random.action.errors")
                .description("Counts how many simulated errors occurred")
                .register(registry);
        this.latencySpikeCounter = Counter.builder("incident.latency.spikes")
                .description("Number of latency spikes during incident simulation")
                .register(registry);

        this.cpuSpikeCounter = Counter.builder("incident.cpu.spikes")
                .description("Number of CPU spikes during incident simulation")
                .register(registry);

        this.replayMetricCounter = Counter.builder("replay.generated.events")
                .description("Number of simulated events generated by the replay endpoint")
                .register(registry);
    }


    @PostConstruct
    public void setupOpenTelemetry() {
        LoggingSpanExporter spanExporter = new LoggingSpanExporter();
        OpenTelemetrySdk sdk = OpenTelemetrySdk.builder()
                .setTracerProvider(SdkTracerProvider.builder()
                        .addSpanProcessor(SimpleSpanProcessor.create(spanExporter))
                        .build())
                .buildAndRegisterGlobal();

        this.tracer = sdk.getTracer("random-generator");

        logger.info("OpenTelemetry initialized");
    }

    @Scheduled(fixedRate = 5000)
    public void generateRandomTelemetry() {
        if (tracer == null) return;

        Span span = tracer.spanBuilder("generate-random-span").startSpan();
        Random random = new Random();

        try {
            String action = new String[]{"login", "purchase", "search"}[random.nextInt(3)];
            span.setAttribute("action", action);
            span.setAttribute("user.id", random.nextInt(1000));
            logger.info("Random log for action: {}", action);

            metricsController.recordTotalEvent();
            metricsController.recordHttp200();

            boolean simulateError = random.nextDouble() < 0.3;
            if (simulateError) {
                String errorType = new String[]{"TimeoutException", "NullPointerException", "DBConnectionError"}[random.nextInt(3)];
                span.setStatus(io.opentelemetry.api.trace.StatusCode.ERROR, "Simulated error: " + errorType);
                span.setAttribute("error.type", errorType);

                metricsController.recordErrorEvent();
                metricsController.recordLatencySpike();
                metricsController.recordCpuSpike();
                metricsController.recordHttp500();
                logger.error("Simulated ERROR [{}]: {}", action, errorType);
            }

            randomActionCounter.increment();
        } finally {
            span.end();
        }
    }
    @Scheduled(fixedRate = 600_000) // every 10 minutes
    public void autoReplayLast10Mins() {
        Random random = new Random();
        boolean simulateIncident = random.nextDouble() < 0.3;

        logger.info("AUTO REPLAY MODE: {}", simulateIncident ? "🚨 INCIDENT SIMULATION" : "Normal load");

        for (int i = 0; i < 60; i++) {
            String action = new String[]{"login", "purchase", "logout", "search"}[random.nextInt(4)];
            int userId = random.nextInt(1000);
            Instant fakeTime = Instant.now().minusSeconds(600 - (i * 10));

            Span span = tracer.spanBuilder("auto-replay-span-" + i)
                    .setStartTimestamp(fakeTime)
                    .startSpan();

            span.setAttribute("user.id", userId);
            span.setAttribute("action", action);
            span.setAttribute("event.generated_at", fakeTime.toString());

            boolean isError = false;
            String errorType = null;

            if (simulateIncident && i % 7 == 0) {
                isError = true;
                errorType = new String[]{"NullPointerException", "TimeoutException", "DBConnectionError"}[random.nextInt(3)];
                span.setAttribute("incident", true);
                span.setAttribute("error.type", errorType);
                span.setStatus(StatusCode.ERROR);
                errorCounter.increment();

                try {
                    long delay = 1000 + random.nextInt(1000);
                    Thread.sleep(delay);
                    span.setAttribute("latency.spike.ms", delay);
                    latencySpikeCounter.increment();
                } catch (InterruptedException ignored) {}

                long cpuStart = System.nanoTime();
                long durationNs = (100 + random.nextInt(100)) * 1_000_000L;
                while (System.nanoTime() - cpuStart < durationNs) {
                    Math.pow(random.nextDouble(), random.nextDouble());
                }
                span.setAttribute("cpu.spike.ms", durationNs / 1_000_000);
                cpuSpikeCounter.increment();

                logger.error("AUTO INCIDENT [{}]: userId={}, action={}, errorType={}", i, userId, action, errorType);
            } else {
                logger.info("AUTO REPLAY [{}]: userId={}, action={}, at={}", i, userId, action, fakeTime);
            }

            metricsController.recordTotalEvent();
            metricsController.recordHttp200();
            if (isError) {
                metricsController.recordErrorEvent();
                metricsController.recordHttp500();
                metricsController.recordLatencySpike();
                metricsController.recordCpuSpike();
            }

            traceStore.addTrace(new TraceEvent(
                    span.getSpanContext().getTraceId(),
                    span.getSpanContext().getSpanId(),
                    action,
                    userId,
                    fakeTime,
                    isError,
                    errorType
            ));

            replayMetricCounter.increment();
            span.end();
        }
    }


}
